services:
    db:
        image: mysql:8.0
        container_name: copromanager-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: change_me_root
            MYSQL_DATABASE: coprodb
            MYSQL_USER: copro
            MYSQL_PASSWORD: change_me
        volumes:
            - db-data:/var/lib/mysql
        expose:
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - appnet

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: copromanager-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        expose:
            - "80"
        depends_on:
            - db
        networks:
            - appnet

    backend:
        image: axelfertinel/copro-backend:latest
        container_name: copromanager-backend
        restart: unless-stopped
        env_file:
            - ./backend/.env
        depends_on:
            - db
        expose:
            - "3000"
        networks:
            - appnet

    frontend:
        image: axelfertinel/copro-frontend:latest
        container_name: copromanager-frontend
        restart: unless-stopped
        environment:
            NODE_ENV: production
        depends_on:
            - backend
        expose:
            - "80"
        networks:
            - appnet

volumes:
    db-data:

networks:
    appnet:
        driver: bridge
